export const GET_ALL_BOOKING_REQUESTS_REQUEST = "GET_ALL_BOOKING_REQUESTS_REQUEST"
export const GET_ALL_BOOKING_REQUESTS_SUCCESS = "GET_ALL_BOOKING_REQUESTS_SUCCESS"
export const GET_ALL_BOOKING_REQUESTS_FAIL = "GET_ALL_BOOKING_REQUESTS_FAIL"

export const UPDATE_BOOKING_REQUEST_STATUS_REQUEST = "UPDATE_BOOKING_REQUEST_STATUS_REQUEST"
export const UPDATE_BOOKING_REQUEST_STATUS_SUCCESS = "UPDATE_BOOKING_REQUEST_STATUS_SUCCESS"
export const UPDATE_BOOKING_REQUEST_STATUS_FAIL = "UPDATE_BOOKING_REQUEST_STATUS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"