export const APPLY_LEAVE_REQUEST = "APPLY_LEAVE_REQUEST"
export const APPLY_LEAVE_SUCCESS = "APPLY_LEAVE_SUCCESS"
export const APPLY_LEAVE_FAIL = "APPLY_LEAVE_FAIL"

export const ALL_LEAVES_REQUEST = "ALL_LEAVES_REQUEST"
export const ALL_LEAVES_SUCCESS = "ALL_LEAVES_SUCCESS"
export const ALL_LEAVES_FAIL = "ALL_LEAVES_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"