export const GET_ALL_SERVICES_REQUESTS = "GET_ALL_SERVICES_REQUESTS"
export const GET_ALL_SERVICES_SUCCESS = "GET_ALL_SERVICES_SUCCESS"
export const GET_ALL_SERVICES_FAIL = "GET_ALL_SERVICES_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"